chef/mixlib-archive

- lib/mixlib/archive.rb
- lib/mixlib/archive/tar.rb
- mixlib-archive.gemspec
Signed-off-by: Thom May <thom@may.lt>
> Add logging

- lib/mixlib/archive.rb
- lib/mixlib/archive/tar.rb
- spec/mixlib/archive_spec.rb
> Create archives as well as extracting them

- CHANGELOG.md
- lib/mixlib/archive/version.rb
Signed-off-by: Thom May <thom@may.lt>
> Release 0.4.1

- .travis.yml
> Test on Ruby 2.5 and the latest ruby patch releases

- README.md
Seems obvious but makes this super copy/paste-able
> Add the require to the example

- README.md
> Fix the examples to actually work

- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
> Update codeowners and add PR template

- lib/mixlib/archive.rb
- spec/mixlib/archive_spec.rb
Signed-off-by: Thom May <thom@may.lt>
> Ensure that paths like foo..bar.baz aren't ignored

- .expeditor/config.yml
We need this for windows hosts.
> Publish the mixlib-archive-universal-mingw32 gem as well

- mixlib-archive.gemspec
There's no need for this file.
> Don't ship the readme in the gem artifact

- .expeditor/config.yml
- Gemfile
> Update expeditor config and order gemfile

- .expeditor/config.yml
- .expeditor/verify.pipeline.yml
> Add PR testing with Build Kite

- CONTRIBUTING.md
- appveyor.yml
> Add Ruby 2.6 testing in Appveyor

- .expeditor/verify.pipeline.yml
- .github/CODEOWNERS
- Gemfile
- Rakefile
- appveyor.yml
Optimize Appveyor and Buildkite CI
> Speed up CI

- .expeditor/config.yml
- .expeditor/run_linux_tests.sh
- .expeditor/verify.pipeline.yml
- .github/ISSUE_TEMPLATE/BUG_TEMPLATE.md
- .github/ISSUE_TEMPLATE/DESIGN_PROPOSAL.md
- README.md
Use Debian 10 images
Cache gem installs
Add more labels to GitHub templates
> Test on Ruby 2.7rc and other testing updates

- .expeditor/run_linux_tests.sh
- mixlib-archive.gemspec
> Remove encoding comment we don't need

- README.md
> Add a note about ffi-libarchive to the readme

- Gemfile
- mixlib-archive-universal-mingw32.gemspec
- mixlib-archive.gemspec
- spec/spec_helper.rb
> Update Chefstyle to 1.6.2

- .expeditor/run_linux_tests.sh
- .expeditor/verify.pipeline.yml
- Gemfile
- Rakefile
Modernize how we test here a bit
> Cache gems and test on Ruby 3

- .expeditor/run_windows_tests.ps1
- .expeditor/verify.pipeline.yml
Signed-off-by: poornima <poorndm@progress.com>
> Add ruby-3.0/3.1 tests on windows
